### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by prashantnirgun** [techformist/featherlight-crm#25]
Hi Prashanth from Prashant 

I am very sorry its not an Issue just need help from you. I read your post on feathers its a very informative article, good work keep it up. I checked the vue part also. I installed  "@feathersjs/feathers": "^4.5.11". Now my question is If I want to write routes http://localhost:3000/contact/india or any custom endpoint for GET, POST methods where do I write can you guide me. Basically wants a controller but that does not mean I want to use create() and other methods of Objection should fire automatically don't want to override the methods provided by Objection.js

I know we can query it by http://localhost:3000/contact?country="India" but need need build custom routes.

**Comment by prashanth1k** [comment]
Hi Prashant, sorry - I missed this. Been focusing elsewhere nowadays.
You may have already gotten this answer from the great web. In Feathers I would typically do `feathers generate service` and start changing files in the specific folder (e.g. [activities hook](https://github.com/techformist/featherlight-crm/blob/master/server/src/services/activities/activities.hooks.js)). If I want to do something generic, I would probably use a second service that can process different objects based on route - but I haven't really done that (or would do in that way).
